# -*- coding: utf-8 -*-
"""03_QSE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwZRT8A6oNNaVWs3Q-3m9JkSSaTnietj
"""

!pip install -q qiskit
!pip install -q qiskit-aer
!pip install -q qiskit-algorithms
!pip install -q qiskit-nature
!pip install -q qiskit-nature-pyscf
!pip install -q pyscf
!pip install -q scipy matplotlib

import numpy as np
from scipy.linalg import eigh
from qiskit.quantum_info import SparsePauliOp, Statevector
from qiskit_nature.second_q.mappers import JordanWignerMapper
from qiskit_nature.second_q.operators import FermionicOp

print("All imports successful!")

h = SparsePauliOp(['IIII', 'IIIZ', 'IIZI', 'IZII', 'ZIII', 'IIZZ', 'IZIZ', 'ZIIZ', 'YYYY', 'XXYY', 'YYXX', 'XXXX', 'IZZI', 'ZIZI', 'ZZII'],
              coeffs=[-0.67810865+0.j,  0.07683157+0.j, -0.07802605+0.j,  0.07683157+0.j,
 -0.07802605+0.j,  0.08418098+0.j,  0.12685108+0.j,  0.12720766+0.j,
  0.04302668+0.j,  0.04302668+0.j,  0.04302668+0.j,  0.04302668+0.j,
  0.12720766+0.j,  0.13086927+0.j,  0.08418098+0.j])

hamiltonian = h
print(f"Hamiltonian: {hamiltonian.num_qubits} qubits, {len(hamiltonian)} terms")

statevector_array = np.array([
    -1.20435792e-03-1.24000232e-03j,
     5.90184494e-03-1.68564974e-03j,
     1.44348600e-03+4.39195673e-04j,
    -5.58947069e-03-4.50609562e-03j,
    -8.49377756e-04+2.29394815e-04j,
     6.97860409e-01+6.70071228e-01j,
    -3.93437104e-03-1.58009705e-03j,
    -6.57431026e-03+3.82047989e-03j,
    -6.43745293e-04-2.70724107e-04j,
     4.72150010e-03+1.25159244e-03j,
    -1.80238812e-01-1.73903623e-01j,
    -1.15342310e-03+5.84675480e-04j,
     6.86917125e-03+3.17232114e-02j,
    -1.10959401e-04+8.21756795e-04j,
    -1.03189882e-03+3.76601683e-03j,
    -5.46607973e-04-2.15358538e-04j
])

statevector = Statevector(statevector_array)

# Verify energy
vqe_energy = statevector.expectation_value(hamiltonian).real
print(f"VQE energy from statevector: {vqe_energy:.8f} Ha")
print(f"Statevector norm: {np.linalg.norm(statevector_array):.6f}")

# Build excitation pool with identity
n_spin = 4

# Identity operator (critical for ground state inclusion)
op_identity = FermionicOp({'' : 1.0}, num_spin_orbitals=n_spin)

# Single excitations (spin-conserving)
op_single_alpha = FermionicOp({'+_2 -_0': 1.0}, num_spin_orbitals=n_spin)  # α: 0→1
op_single_beta  = FermionicOp({'+_3 -_1': 1.0}, num_spin_orbitals=n_spin)   # β: 0→1

# Double excitation (move both electrons)
op_double = FermionicOp({'+_2 +_3 -_1 -_0': 1.0}, num_spin_orbitals=n_spin)

# Pool with identity first
fermi_pool = [op_identity, op_single_alpha, op_single_beta, op_double]

# Map to Pauli strings
mapper = JordanWignerMapper()
pauli_pool = [mapper.map(op) for op in fermi_pool]

print(f"Number of operators: {len(pauli_pool)}")
for i, op in enumerate(pauli_pool):
    print(f"O_{i}: {op}")

# Build H and S matrices
n_ops = len(pauli_pool)
H_mat = np.zeros((n_ops, n_ops), dtype=complex)
S_mat = np.zeros((n_ops, n_ops), dtype=complex)

for i in range(n_ops):
    Oi = pauli_pool[i]
    Oi_dag = Oi.conjugate().transpose()
    for j in range(n_ops):
        Oj = pauli_pool[j]

        # Overlap matrix: <Ψ| Oi† Oj |Ψ>
        overlap_op = Oi_dag @ Oj
        S_val = statevector.expectation_value(overlap_op)
        S_mat[i, j] = S_val

        # Hamiltonian matrix: <Ψ| Oi† H Oj |Ψ>
        H_Oj = hamiltonian @ Oj
        full_op = Oi_dag @ H_Oj
        H_val = statevector.expectation_value(full_op)
        H_mat[i, j] = H_val

# Take real parts (should be Hermitian)
S_real = np.real(S_mat)
H_real = np.real(H_mat)

print("S matrix (should have 1 on diagonal for identity):")
print(S_real)
print("\nH matrix:")
print(H_real)

# Verification
print(f"S is Hermitian: {np.allclose(S_real, S_real.T)}")
S_eigvals = np.linalg.eigvalsh(S_real)
print(f"Smallest eigenvalue of S: {S_eigvals.min():.6f} (should be > 0)")

# Check that identity operator gives correct energy
# The first row/column should correspond to identity
# The (0,0) element of H should equal VQE energy
print(f"\nH[0,0] (from identity-identity): {H_real[0,0]:.8f} Ha")
print(f"VQE energy: {vqe_energy:.8f} Ha")
print(f"Difference: {abs(H_real[0,0] - vqe_energy):.2e} Ha")

# --- Solve H v = E S v ---
try:
    eigvals, eigvecs = eigh(H_real, S_real)
except np.linalg.LinAlgError as e:
    print("S is singular. Adding small regularization...")
    S_reg = S_real + 1e-10 * np.eye(len(S_real))
    eigvals, eigvecs = eigh(H_real, S_reg)

print("\nEigenvalues (Hartree):")
for i, val in enumerate(eigvals):
    print(f"  E_{i} = {val:.8f} Ha")

# Extract excitation energy
E0_qse = eigvals[0]
E1_qse = eigvals[1] if len(eigvals) > 1 else None

print(f"QSE ground energy: {E0_qse:.8f} Ha")
print(f"VQE ground energy: {vqe_energy:.8f} Ha")
print(f"Difference: {abs(E0_qse - vqe_energy):.2e} Ha")

if E1_qse is not None:
    delta_E_ha = E1_qse - E0_qse
    delta_E_ev = delta_E_ha * 27.2114
    print(f"\nFirst excited energy: {E1_qse:.8f} Ha")
    print(f"Vertical excitation energy: {delta_E_ev:.4f} eV")
    print(f"Literature value: ~7.6 eV")
    print(f"Deviation: {abs(delta_E_ev - 7.6):.4f} eV")
else:
    print("Only one eigenvalue found – need more operators.")